files:
"/home/.ssh/config" :
mode: "000600"
owner: root
group: root
content: |
Host bitbucket.org
User git
Hostname bitbucket.org
IdentityFile /home/.ssh/bitbucket.org

"/home/.ssh/known_hosts" :
mode: "000644"
owner: root
group: root
content: |
GQRGuSusMEASYiWunYN0vCAI8QaXnWMXNMdFP3jHAJH0eDsoiGnLPBlBp4TNm6rYI74nMzgz3B9IikW4WVK+dc8KZJZWYjAuORU3jc1c/NPskD2ASinf8v3xnfXeukU0sJ5N6m5E8VLjObPEO+mN2t/FZTMZLiFqPWc/ALSqnMnnhwrNi2rbfg/rd/IpL8Le3pSBne8+seeFVBoGqzHM9yXw==

"/home/.ssh/bitbucket.org" :
mode: "000644"
owner: root
group: root
source : "https://s3-eu-west-1.amazonaws.com/com.thud.test/bitbucket.org"


